### PR TITLE
adding bower file

### LINKED ISSUE #87: Make available via bower
Hey,

I am not writing a node app, so I actually get all my components via bower. Can you please make this package available via bower, so I can easily get it? Thanks.

### PR DESCRIPTION
**Pull request by lukasoppermann**
A **bower.json** so it can be installed via bower.

However, once this is merged, I think you will need to run 
`bower register ajax-form https://github.com/rnicholus/ajax-form.git` from the cli. I am not sure if I can do it. But I can try. ;-)

Fixed #87

### CODE REVIEW

**Comment by rnicholus** [comment]
Actually, this may not be entirely necessary (though probably appropriate), since I already registered ajax-form w/ bower a while back. Running `bower install ajax-form` pulls down 2.1.3 (the current version).

**Comment by lukasoppermann** [comment]
Hmm, it does work, however I would still think it is better to have the json file because:
1. people know its on bower
2. it is easier to find due to tags, etc

**Comment by rnicholus** [comment]
Agreed. I'll try to look this over in the next couple days or so and will then merge this in if all looks good. No version update is needed after merge, as far as I can tell. Don't worry about the failing build - pull requests can't be tested against Sauce Labs due to a common auth issue.

**Comment by rnicholus** [comment]
Thanks @lukasoppermann!

**Pull request merged**
