### PR TITLE
Add support to the input form as an array name

### PR DESCRIPTION
**Pull request by jonataa**
I tried using the code below, but it only send the last checkbox (not checked).
```html
<input type="checkbox" name="checkbox1[]" value="foo" checked>
<input type="checkbox" name="checkbox1[]" value="bar" checked>
<input type="checkbox" name="checkbox1[]" value="fizz">
```
Also, It isn't working for the input field as array format names. This link can help to understand: http://stackoverflow.com/questions/4709926/how-can-i-use-the-array-format-input-field-names-in-my-html-form-that-posts-to-p

I done some changes in the ajax-form.js to support it, but be will need update the current tests. I have not sure if this is better way. Make sense?

### CODE REVIEW

**Comment by rnicholus** [comment]
Thanks for this.  It might be a while before I can look at this closer.  I'm a bit overcommitted at the moment.

**Comment by rnicholus** [comment]
I'm starting to look into this now as the last task to complete before releasing ajax-form 2.0.

**Comment by rnicholus** [comment]
Completed, and about to be part of ajax-form 2.0.

**Comment by jonataa** [comment]
Awesome!! Thanks, @rnicholus!

**Comment by rnicholus** [comment]
I threw this together in about an hour earlier today, but it's covered by the unit tests. Let me know if anything isn't quite right.

**Pull request closed without merging**
